
# Server configuration
server.port=8083
spring.application.name=chatbot

# MongoDB configuration
spring.data.mongodb.uri=mongodb+srv://viddeveloper6:test%4012@chat.j4x59.mongodb.net/chatbot?retryWrites=true&w=majority&appName=chat&ssl=false
spring.data.mongodb.database=chatbot

# Spring Boot DevTools configuration (optional for hot reloading during development)
spring.main.allow-bean-definition-overriding=true
spring.devtools.restart.enabled=true

# Exclude unwanted auto-configuration if necessary
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Logging configuration (optional for debugging)
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.org.springframework.ai=DEBUG
spring.web.cors.allowed-origins=http://localhost:3000, http://example.com
spring.web.cors.allowed-methods=GET, POST, PUT, DELETE
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true



